services:
  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: jaeger-poc
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "14317:4317"
      - "14318:4318"
      - "16686:16686"
